apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 1
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.20.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: ""
